version: "3.8"
services:
  mongo1:
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --replSet rs0 --bind_ip 0.0.0.0
    volumes:
      - mongo1-data:/data/db
    networks:
      - banking-network
  mongo2:
    image: mongo
    ports:
      - "27018:27017"
    command: mongod --replSet rs0 --bind_ip 0.0.0.0
    volumes:
      - mongo2-data:/data/db
    networks:
      - banking-network
  mongo3:
    image: mongo
    ports:
      - "27019:27017"
    command: mongod --replSet rs0 --bind_ip 0.0.0.0
    volumes:
      - mongo3-data:/data/db
    networks:
      - banking-network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - banking-network
volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
networks:
  banking-network: